name: Create thumbnails
on: [push]
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: login_to_ghcr.io
        uses: docker/login-action@v1.8.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          logout: true>